services:
  - type: web
    name: django-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn calcproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dictproject.settings
